name: Jest Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: yarn install
      - run: yarn install
      - name: jest test
      - run: yarn run test
      - name: if fail
        if: failure()